const traits = [
  "Active", "Adaptable", "Adventurous", "Affectionate", 
  "Aggressive", "Alert", "Ambitious", "Analytical", 
  "Anxious", "Apathetic","Appreciative", "Arrogant", 
  "Articulate", "Artistic", "Assertive", "Attentive", 
  "Audacious", "Austere", "Authentic", "Balanced",
  "Benevolent", "Bitter", "Blunt", "Boastful", 
  "Bold", "Bossy", "Brave", "Bright", 
  "Broad-minded", "Callous","Calm", "Candid", 
  "Capable", "Carefree", "Careful", "Careless", 
  "Caring", "Cautious", "Charismatic", "Charming",
  "Cheerful", "Childish", "Clever", "Clumsy", 
  "Cold", "Collaborative", "Compassionate", "Competitive", 
  "Confident", "Conscientious", "Considerate", "Cooperative", 
  "Courageous", "Courteous", "Cowardly", "Creative", 
  "Critical", "Cruel", "Curious", "Cynical",
  "Daring", "Decisive", "Dedicated", "Defiant", 
  "Deliberate", "Dependable", "Detached", "Determined", 
  "Devoted", "Diplomatic", "Disciplined", "Disloyal", 
  "Disorganized", "Disrespectful", "Dominant", "Dramatic", 
  "Duty-bound", "Eager", "Earnest", "Easygoing",
  "Eccentric", "Efficient", "Egocentric", "Egotistical", 
  "Elitist", "Empathetic", "Energetic", "Enthusiastic", 
  "Envious", "Ethical", "Exacting", "Excitable", 
  "Extroverted", "Fair", "Faithful", "Fierce", "Flexible", 
  "Forgiving", "Frank", "Friendly", "Frugal", 
  "Generous", "Gentle", "Gloomy", "Good-natured", 
  "Greedy", "Grumpy", "Gullible", "Hardworking", 
  "Humble", "Humorous", "Hyperactive", "Idealistic", 
  "Impatient", "Impolite", "Impulsive", "Inconsiderate", 
  "Independent", "Indecisive", "Indifferent", "Individualistic",
  "Industrious", "Inflexible", "Ingenious", "Insecure", 
  "Insightful", "Insolent", "Inspiring", "Intelligent", 
  "Introverted", "Intuitive", "Inventive", "Irresponsible", 
  "Irritable", "Jealous", "Jovial", "Judgemental", 
  "Keen", "Kind", "Lazy", "Leaderly",
  "Lethargic", "Liberal", "Lighthearted", "Lively", 
  "Logical", "Loyal", "Malicious", "Manipulative", 
  "Materialistic", "Mature", "Mean", "Meek", 
  "Melancholy", "Meticulous", "Mild", "Mischievous", 
  "Modest", "Moody", "Naive", "Narcissistic",
  "Narrow-minded", "Neat", "Negative", "Negligent", 
  "Neurotic", "Objective", "Obliging", "Observant", 
  "Obsessive", "Obstinate", "Open-minded", "Optimistic", 
  "Organized", "Outgoing", "Outspoken", "Passionate", 
  "Passive", "Patient", "Perceptive", "Perfectionist",
  "Persevering", "Persistent", "Pessimistic", "Philosophical", 
  "Polite", "Possessive", "Practical", "Pragmatic", 
  "Precise", "Prejudiced", "Pragmatic", "Protective", 
  "Proud", "Punctual", "Rational", "Realistic", 
  "Rebellious", "Reckless", "Reflective", "Reliable",
  "Resentful", "Resilient", "Resourceful", "Respectful", 
  "Responsible", "Restless", "Rigid", "Romantic", 
  "Rude", "Sarcastic", "Secretive", "Self-centered", 
  "Self-confident", "Self-conscious", "Self-disciplined", "Selfish", 
  "Selfless", "Sensitive", "Sentimental", "Sincere",
  "Skeptical", "Sloppy", "Sociable", "Spiteful", 
  "Spontaneous", "Stable", "Strict", "Stubborn", 
  "Submissive", "Supportive", "Sympathetic", "Tactful", 
  "Talkative", "Thoughtful", "Timid", "Tolerant", 
  "Trustworthy", "Unpredictable", "Vain", "Warm"
];

module.exports = {
    traits
}